entity-protection:
  #좀비나 스켈레톤같은 불에 타는 몹을 보호할것인지
  protect-zombie: true
  protect-skeleton: true

block:
  #블럭 부술 시 번개가 칠 확률과 tnt의 폭발 시간
  lightning-chance: 0.1
  tnt-fuse-ticks: 80

creeper:
  #크리퍼의 폭발에 대한 세세한 config
  explosion-radius-per-tick: 0.5
  explosion-point-per-circum: 6.0
  explosion-duration-ticks: 100
  explosion-power: 4.0

Weather:
  lightning-chance: 0.0001
  damage-count: 0.1
  damage-noDamageTicks: 0
  damage-TickRate: 1
  Thunder-TickRate: 200

Zombie:
  #좀벌레를 소환하는 확률과 소환하는 갯수
  spawn-EnderMite: 2
  spawn-Chance: 100

  #좀비의 기본 능력치
  attri-health: 100
  attri-damage: 6

  #엔더마이트의 기본 능력치
  zom-he: 8
  zom-da: 3

Skeleton:
  #화살을 발사하는 간격
  skeleton-arrow-tick: 1

  #한번에 발사하는 화살의 갯수
  skeleton-arrow-num: 10

  #스켈레톤의 기본 능력치
  attri-health: 50

worldBorder:
  speed: 0.01
